# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvector.proto\x12\tpb.vector\x1a\x1egoogle/protobuf/wrappers.proto\"/\n\x11\x44\x61taVectorRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t2W\n\x06Vector\x12M\n\x0fStoreToVectorDB\x12\x1c.pb.vector.DataVectorRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x42+Z)github.com/vnnyx/real-time-data/pb/vectorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/vnnyx/real-time-data/pb/vector'
  _globals['_DATAVECTORREQUEST']._serialized_start=59
  _globals['_DATAVECTORREQUEST']._serialized_end=106
  _globals['_VECTOR']._serialized_start=108
  _globals['_VECTOR']._serialized_end=195
# @@protoc_insertion_point(module_scope)
